### ISSUE TITLE
Add Maze Movement System

### ISSUE THREAD

**Issue by jonhartnett** [dbnorth/Maze#20]
Add a separate thread for the maze instance that performs movement on time ticks from a queue. The maze move method will add events to the queue and sleep until the movement is complete.

**Comment by dbnorth** [comment]
When the droid enters the maze it seems the Maze should assign the droid a speed that can be the basis for this movement.  It can be the same speed for all droids for now and when we get the mechanism for getting different speeds then it can be made more dynamic.
